# Generated by Django 5.2.7 on 2025-11-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaltestresult',
            old_name='predict_disorder',
            new_name='predicted_disorder',
        ),
    ]
